### ISSUE TITLE
Feature request: standalone python connectivity example

### ISSUE THREAD

**Issue by snowch** [ibm-messaging/message-hub-samples#10]
It would be good to see a standalone python example for connecting to Message Hub.

**Comment by snowch** [comment]
For an example, see here http://stackoverflow.com/a/40325181/1033422

**Comment by mimaison** [comment]
Hi @snowch,

Thanks for the suggestion. We will likely add a Python sample in the future. In the meantime, we can confirm several clients work out of the box. We've successfully  tested:
* https://github.com/confluentinc/confluent-kafka-python
* https://github.com/dpkp/kafka-python

**Comment by mimaison** [comment]
We've now added a Python sample: https://github.com/ibm-messaging/message-hub-samples/tree/master/kafka-python-console-sample

Closing this issue
