### ISSUE TITLE
https://github.com/ibm-messaging/message-hub-samples/tree/master/java/message-hub-kafka-ssl docs unclear

### ISSUE THREAD

**Issue by brresnic** [ibm-messaging/message-hub-samples#12]
Trying to understand how to populate ssl.truststore.locationias is a major painpoint for me. 

It would be nice to see an example of what this filepath would actually look like on a mac and pc. Some more elaboration on this point in the youtube tutorial would also be helpful.

**Comment by brresnic** [comment]
Additionally, I would be far less likely to churn if this sample was generated for me from within the bluemix microservice, with the config prepopulated according to my credentials. Long time to value

**Comment by mimaison** [comment]
Hi @brresnic 
To use Message Hub you don't have to set any truststore properties. Java will use the default truststore that contains the needed certificates.

We are in the process of revamping the samples, hopefully the next update sometime next week should make this clearer

**Comment by mimaison** [comment]
We've removed mentions of "ssl.truststore.location" as this configuration is not required for the samples to work -> closing
