### ISSUE TITLE
node-rdkafka 0.8.0 fails to connect because of SASL Handshake not supported by broker

### ISSUE THREAD

**Issue by dennisseidel** [ibm-messaging/message-hub-samples#16]
I wanted to upgrade the node.js sample to the most up to date version (0.8.0) of node-rdkafka but it seems there has been an incompatible change in the way how SASL authentication is handle. It produces the following error: 

`{ severity: 3,
  fac: 'FAIL',
  message: '[thrd:sasl_ssl://kafka05-prod01.messagehub.services.us-south.bluemix.]: sasl_ssl://kafka05-prod01.messagehub.services.us-south.bluemix.net:9093/bootstrap: Failed to initialize SASL authentication: SASL Handshake not supported by broker (required by mechanism PLAIN): try api.version.request=true' }`

**Comment by dennisseidel** [comment]
Ok the solution seems to be to change the parameter a bit to the following:

'metadata.broker.list': opts.brokers,
        'security.protocol': '**SASL_SSL**',
        'ssl.ca.location': opts.calocation,
        'sasl.mechanisms': 'PLAIN',
        'sasl.username': opts.username,
        'sasl.password': opts.password,
        **'api.version.request': true**

then it works.

**Comment by mimaison** [comment]
Yes we plan to update our sample app in the next few weeks. 
Is there a particular feature you need from node-rdkafka 0.8 ? If not, we recommend you stick with 0.6.3  for now as it's the version we've tested the most.

**Comment by dennisseidel** [comment]
@mimaison Thanks for the answer. Not specifically I was just using node-rdkafka and did not take a look which version you used, so I was confused when it did not work :) 

But it seems that: 
'metadata.broker.list': opts.brokers,
        'security.protocol': '**SASL_SSL**',
        'ssl.ca.location': opts.calocation,
        'sasl.mechanisms': 'PLAIN',
        'sasl.username': opts.username,
        'sasl.password': opts.password,
        **'api.version.request': true**

works. But also the structure of the message object has change.

**Comment by mimaison** [comment]
@dennisseidel We've now updated the Nodejs sample to run the latest node-rdkafka (0.10).
Closing this, if you still have issues, feel free to re-open
