### ISSUE TITLE
Message hub docker for local testing

### ISSUE THREAD

**Issue by hungtv55** [ibm-messaging/message-hub-samples#21]
Hi there,

I'm using `node-rdkafka` to connect to message hub following to this example: https://github.com/ibm-messaging/message-hub-samples/tree/master/kafka-nodejs-console-sample

Now, i would like to have a Docker image of message hub for local testing purpose. I have tried with this [Kafka docker image](https://github.com/wurstmeister/kafka-docker) but couldn't create a message hub in local.
I wonder if we have a message hub docker for local testing (something like we have for mqlight)?
Do you have any suggestion please?

**Comment by mimaison** [comment]
Message Hub only runs on IBM Cloud, there is no "local" version available.
