### ISSUE TITLE
MirrorMaker Kafka 0.9 connection to Kafka Brokers 0.10 (IBM Message Hub)

### ISSUE THREAD

**Issue by edo1991** [ibm-messaging/message-hub-samples#24]
Hi,
I am trying to connect my MirroMaker Kafka 0.9 to the Kafka Brokers 0.10 (IBM Message Hub) without success.
The links I have followed are the followings, but they are mostly for Kafka clients 0.10:
https://console.bluemix.net/docs/services/MessageHub/messagehub050.html#kafka_using
https://console.bluemix.net/docs/services/MessageHub/messagehub063.html#kafka_connect

Do you know the steps for Kafka clients 0.9 and how to use the MessageHubLoginModule and the jaas creation?

Thank you,
Edoardo

**Comment by mimaison** [comment]
I see you posted the same question on StackOverflow: https://stackoverflow.com/questions/49678502/mirrormaker-kafka-0-9-connection-to-kafka-brokers-0-10-ibm-message-hub/49693275#49693275

I've replied there so I'm closing this issue.
