### ISSUE TITLE
login library on a maven repo

### ISSUE THREAD

**Issue by cjolif** [ibm-messaging/message-hub-samples#4]
Would be good to publish messagehub.login-1.0.0.jar to a maven reposistory so that applications can directly reference it instead of having to getting it from here.

**Comment by zpappa** [comment]
Agreed - it's a pain that I can't pull this from a maven repo - you can do this in mixed mode with sbt but it's a bit of extra and unnecessary work.

**Comment by niall-weedon** [comment]
The samples now use the Kafka 0.10.x library, which no longer require the Message Hub login library.

Thanks!

**Comment by cjolif** [comment]
so you might probably want to remove it from here: https://github.com/ibm-messaging/message-hub-samples/tree/master/java/message-hub-liberty-sample/lib-message-hub if the sample does not use it anymore?

**Comment by cjolif** [comment]
So I did  a similar move on my code and it now fails with errors such as:

```
2016-08-28T21:58:39.28+0200 [App/0]      OUT WARN 2016-08-28 19:58:39,282 90516 org.apache.kafka.clients.NetworkClient [Thread-20] Bootstrap broker kafka01-prod01.messagehub.services.us-south.bluemix.net:9093 disconnected
```

The liberty sample here is working _but_ if I modify it to subscribe to a pattern instead (like my app is doing) then it has the same issue as my own code. You'll reproduce the problem by changing:

```
kafkaConsumer.subscribe(topicList,
```

by

```
kafkaConsumer.subscribe(Pattern.compile("testTopic"),
```

in your sample.

Looks like there is a regression somewhere because it used to work fine?

**Comment by cjolif** [comment]
Not that I setup a local Kafka 0.10 and I don't reproduce the problem, so it seems to be somewhat MessageHub specific?

**Comment by mimaison** [comment]
@cjolif Although we recommend all our users to move to the new 0.10 client, we still support 0.9 clients hence keep a copy of our login module here.

Regarding the issue with pattern subscription, we've found the problem and the fix will reach production within a few days.
