### ISSUE TITLE
Message hub service goes down everyday

### ISSUE THREAD

**Issue by harishvarma8055** [ibm-messaging/message-hub-samples#9]
Iam using message hub service for a project.Iam running in to an issue that message hub service goes down everyday and the app needs to be started everyday.How can I handle this.

Unable to consume topic: Error: Request returned status code 502 but it was not in the accepted list.
2016-10-20T10:32:13.768+0530[App/0]OUTgot error: { [Error: Request returned status code 502 but it was not in the accepted list. ] statusCode: 502 }

Can someone help if they are using messagehub for production and how they are handling this kind of thing.

**Comment by mimaison** [comment]
Hi @harishvarma8055,
Yes the REST API is restarted everyday as stated in our documentation under "Known restrictions": https://console.ng.bluemix.net/docs/services/MessageHub/ts_overview.html#messagehub057

We don't recommend using the REST API for production usages but instead only as a way to get started quickly. If you want to use Message Hub with Nodejs, I'd suggest you to check: https://github.com/Blizzard/node-rdkafka
We are currently building a sample application with this client and it should be published within the next couple of weeks.
